# Generated by Django 4.2 on 2023-08-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='exclusive',
            field=models.BooleanField(default=False),
        ),
    ]
