# Generated by Django 4.2 on 2023-08-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_fooditem_exclusive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='exclusive',
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.CharField(choices=[('breakfirst', 'breakfirst'), ('lunch', 'lunch'), ('dinner', 'dinner'), ('snack', 'snacks'), ('exclusive', 'exclusive')], max_length=20),
        ),
    ]
