# Generated by Django 4.2 on 2023-08-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_fooditem_exclusive_alter_fooditem_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=30)),
                ('fb_link', models.CharField(blank=True, max_length=100, null=True)),
                ('tw_link', models.CharField(blank=True, max_length=100, null=True)),
                ('ins_link', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
