# Generated by Django 4.2 on 2023-08-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_chef'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='chef_img',
            field=models.ImageField(blank=True, null=True, upload_to='chefs'),
        ),
    ]
