# Generated by Django 4.2 on 2023-08-27 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_customer_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='add',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pic/profile1.png', null=True, upload_to='profile_pic'),
        ),
    ]
