# Generated by Django 4.2 on 2023-08-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_orderplaced_add_alter_customer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
